### ISSUE TITLE
Documentation: blockapps.net/api is inaccurate

### ISSUE THREAD

**Issue by kjameslubin** [blockapps/strato-api#41]
+ /faucet creates GET params instead of POST params and therefore doesn't work
+ /wallet GET and POST params aren't documented
+ /register query params should be POST params like /faucet - same problem as there, likely

We should consider adding documentation checks to CI as we start putting CI in. Our documentation is  DRY now but should generate accurate sample code

**Comment by kejace** [comment]
This is partially fixed by pull-request #34
