### ISSUE TITLE
SSL connection is failing on many browsers....

### ISSUE THREAD

**Issue by jamshidh** [blockapps/strato-api#63]
@kejace can not get the https page to work on his browser, and after further testing, we've realized that it also doesn't work with curl or lynx.

**Comment by ryanreich** [comment]
Not to mention that there's something wrong with blockapps-js and SSL.

**Comment by kjameslubin** [comment]
Investigated more - this may be a "bundling problem". Adding a label. This one is hard to estimate - I'd say hours but it's hard to predict

**Comment by kjameslubin** [comment]
It appears @jamshidh is working on this. Still labeling `bug`

**Comment by jamshidh** [comment]
I've moved this bug to me....
